# Generated by Django 5.2 on 2025-04-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutubxona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muallif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('jins', models.CharField(choices=[('ERKAK', 'ERKAK'), ('AYOL', 'AYOL')], max_length=20)),
                ('t_sana', models.DateField(blank=True, null=True)),
                ('kitob_soni', models.PositiveSmallIntegerField(null=True)),
                ('tirik', models.BooleanField(default=False)),
            ],
        ),
    ]
