# Generated by Django 5.2 on 2025-04-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutubxona', '0003_kitob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kutubxonachi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('ish_vaqti', models.CharField(choices=[('08:30-12:30', '08:30-12:30'), ('12:30-18:00', '12:30-18:00'), ('18:00-00:00', '18:00-00:00')], default='08:30-12:30')),
            ],
        ),
    ]
