# Generated by Django 5.2 on 2025-04-29 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kutubxona', '0005_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='olingan_sana',
        ),
    ]
