# Generated by Django 5.2 on 2025-04-29 07:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutubxona', '0006_remove_record_olingan_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='olingan_sana',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
