# Generated by Django 5.2 on 2025-05-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohirdev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('daraja', models.CharField(max_length=50)),
                ('ustoz', models.CharField(max_length=255)),
                ('narx', models.FloatField()),
                ('chegirma', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
