# Generated by Django 5.2 on 2025-05-01 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohirdev', '0002_kurs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Izoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField()),
                ('sana', models.DateField(auto_now_add=True)),
                ('baho', models.CharField()),
                ('kurs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mohirdev.kurs')),
                ('profil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mohirdev.profile')),
            ],
        ),
    ]
