# Generated by Django 5.2 on 2025-05-01 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohirdev', '0004_tanlangan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xarid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(auto_now_add=True)),
                ('holat', models.CharField(max_length=255)),
                ('kurs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mohirdev.kurs')),
                ('profil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mohirdev.profile')),
            ],
        ),
    ]
